# Generated by Django 2.2.5 on 2020-02-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('cgpa', models.FloatField()),
                ('marks12', models.FloatField(max_length=250)),
                ('marks10', models.FloatField(max_length=250)),
                ('hack', models.IntegerField()),
                ('internship', models.IntegerField()),
                ('research_exp', models.CharField(choices=[('Yes', '1'), ('No', '0')], max_length=1)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
