# Generated by Django 2.2.5 on 2020-02-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementPrediction', '0002_student_dev_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='company',
        ),
    ]
