# Generated by Django 2.2.5 on 2020-02-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementPrediction', '0003_remove_student_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dev_type',
            field=models.IntegerField(choices=[(0, 'Web'), (1, 'App'), (2, 'Software'), (3, 'ML')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='research_exp',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
