# Generated by Django 2.2.5 on 2020-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementPrediction', '0005_auto_20200222_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='AcolliteP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='AmazonP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='GrofersP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HapticP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MicrosoftP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MorganStanleyP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='OracleP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='QuantifyP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='TCSP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ValveP',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
